export const ALL_ROOM_RETURN_REQUEST = 'ALL_ROOM_RETURN_REQUEST';
export const ALL_ROOM_RETURN_SUCCESS = 'ALL_ROOM_RETURN_SUCCESS';
export const ALL_ROOM_RETURN_FAIL = 'ALL_ROOM_RETURN_FAIL';

export const ADD_ROOM_RETURN_REQUEST = 'ADD_ROOM_RETURN_REQUEST';
export const ADD_ROOM_RETURN_SUCCESS = 'ADD_ROOM_RETURN_SUCCESS';
export const ADD_ROOM_RETURN_FAIL = 'ADD_ROOM_RETURN_FAIL';

export const DELETE_ROOM_RETURN_REQUEST = 'DELETE_ROOM_RETURN_REQUEST';
export const DELETE_ROOM_RETURN_SUCCESS = 'DELETE_ROOM_RETURN_SUCCESS';
export const DELETE_ROOM_RETURN_FAIL = 'DELETE_ROOM_RETURN_FAIL';

export const UPDATE_ROOM_RETURN_REQUEST = 'UPDATE_ROOM_RETURN_REQUEST';
export const UPDATE_ROOM_RETURN_SUCCESS = 'UPDATE_ROOM_RETURN_SUCCESS';
export const UPDATE_ROOM_RETURN_FAIL = 'UPDATE_ROOM_RETURN_FAIL';

export const SEARCH_ROOM_RETURN_REQUEST = 'SEARCH_ROOM_RETURN_REQUEST';
export const SEARCH_ROOM_RETURN_SUCCESS = 'SEARCH_ROOM_RETURN_SUCCESS';
export const SEARCH_ROOM_RETURN_FAIL = 'SEARCH_ROOM_RETURN_FAIL';
